apiVersion: v1
kind: Service
metadata:
  name: aks-ratingsapp-demo
  namespace: ratingsapp
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: aks-ratingsapp-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000